google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/identity_service
    username: root
    password: Quydeptrai123
    driver-class-name: com.mysql.cj.jdbc.Driver